// Public homepage content edited by the local editor.
// This file is safe to publish: do not put private material or personal raw notes here.

window.siteContent = {
  "zh": {
    "profile": {
      "name": "Dale Anfer",
      "initials": "D",
      "title": "个人技术博客",
      "availability": "统计学习 / 数据分析 / 可解释建模",
      "tagline": "记录我如何理解数据结构、识别异常与口径差异，并把分析过程整理成清晰的技术笔记。",
      "bio": "我正在寻找人力资源（HR/HR Analytics）相关的实习机会。我致力于用数据赋能人力资源管理，核心优势在于出色的结构化思维与数据敏感度：能快速对人力数据进行清洗、分布特征识别及异常诊断，精准捕捉底层问题，并转化为清晰、可复核的分析输出，为组织决策提供数据支撑。",
      "email": "catalogicalism@gmail.com",
      "github": "https://github.com/sudoun"
    },
    "ui": {
      "brand": "notes",
      "titleSuffix": "个人技术博客",
      "navWork": "项目",
      "navImplementation": "实现",
      "navWriting": "写作",
      "navAbout": "关于",
      "primaryWork": "阅读文章",
      "primaryProjects": "GitHub 主页",
      "fitPanelKicker": "写作索引",
      "fitPanelTitle": "公开技术笔记",
      "fitTargetLabel": "主题",
      "fitTargetValue": "稳健估计 / HR Analytics EDA / 建模假设",
      "fitEvidenceLabel": "方法",
      "fitEvidenceValue": "用例子、公式、代码、表格和图表解释判断过程",
      "fitGithubLabel": "GITHUB",
      "fitGithubValue": "github.com/sudoun",
      "snapshotRole": "稳健估计",
      "snapshotRoleValue": "用异常值、尾部风险和假设边界理解估计器",
      "snapshotTools": "EDA 笔记",
      "snapshotToolsValue": "先检查字段、缺失、重复和口径，再解释分布",
      "snapshotFocus": "可复现解释",
      "snapshotFocusValue": "把代码、表格、图表和结论放在同一条分析链路里",
      "workEyebrow": "公开写作",
      "workTitle": "精选文章",
      "workSubtitle": "主页聚焦已经审核的公开文章和数据分析笔记。",
      "hrProjectKicker": "公开写作",
      "hrProjectTitle": "数据分析文章",
      "hrProjectSummary": "用公开技术文章展示数据审计、建模假设、图表解释和可复核结论。",
      "hrFactModelLabel": "模型",
      "hrFactModelValue": "非结构化招聘信息 → 字段抽取、权重评分、证据缺口、可解释决策",
      "hrFactStackLabel": "技术",
      "hrFactStackValue": "Python、pandas、可视化、数学符号、技术写作",
      "hrFactStatusLabel": "状态",
      "hrFactStatusValue": "只发布已审核文章，私人草稿和本地材料不公开",
      "hrWorkflowLink": "查看工作流",
      "implementationKicker": "写作过程",
      "implementationTitle": "从原始观察到可复核解释",
      "implementationSubtitle": "公开文章展示分析路径、假设边界和解释过程。",
      "implementationFlowBrowser": "观察",
      "implementationFlowApi": "审计",
      "implementationFlowStore": "结构化",
      "implementationFlowScore": "解释",
      "implementationFlowReview": "表达",
      "implementationCaptureTitle": "观察",
      "implementationCaptureText": "先看变量、定义、缺失、异常值和不确定性，再进入解释。",
      "implementationBackendTitle": "数据审计",
      "implementationBackendText": "在可视化前检查结构、重复、缺失、字段角色和数据质量限制。",
      "implementationDecisionTitle": "解释",
      "implementationDecisionText": "区分描述性模式和因果判断，并把假设写清楚。",
      "implementationWorkspaceTitle": "输出",
      "implementationWorkspaceText": "把分析整理成可读的笔记、表格、图表和简洁说明。",
      "writingEyebrow": "公开写作",
      "writingTitle": "数据分析与统计文章",
      "writingSubtitle": "两篇文章：一篇解释稳健估计，一篇展示 HR Analytics EDA 流程。",
      "aboutEyebrow": "关于",
      "aboutTitle": "实习方向与核心优势",
      "footerLabel": "个人技术博客",
    }
  },
  "en": {
    "profile": {
      "name": "Dale Anfer",
      "initials": "D",
      "title": "Personal Technical Blog",
      "availability": "Statistics / Data Analysis / Explainable Modeling",
      "tagline": "I write technical notes on reading data structure, spotting anomalies and definition gaps, and turning analysis into clear explanations.",
      "bio": "I am looking for internship opportunities related to Human Resources and HR Analytics. I am interested in using data to support people management, with strengths in structured thinking and data sensitivity: cleaning HR data, recognizing distributional patterns, diagnosing anomalies, capturing underlying issues, and turning the analysis into clear, reviewable outputs for organizational decisions.",
      "email": "catalogicalism@gmail.com",
      "github": "https://github.com/sudoun"
    },
    "ui": {
      "brand": "notes",
      "titleSuffix": "Personal Technical Blog",
      "navWork": "Work",
      "navImplementation": "Implementation",
      "navWriting": "Writing",
      "navAbout": "About",
      "primaryWork": "Read Essays",
      "primaryProjects": "GitHub Profile",
      "fitPanelKicker": "Writing index",
      "fitPanelTitle": "Public technical notes",
      "fitTargetLabel": "Topics",
      "fitTargetValue": "Robust estimation / HR Analytics EDA / modeling assumptions",
      "fitEvidenceLabel": "Method",
      "fitEvidenceValue": "Explain judgment through examples, formulas, code, tables, and charts",
      "fitGithubLabel": "GitHub",
      "fitGithubValue": "github.com/sudoun",
      "snapshotRole": "Statistical sense",
      "snapshotRoleValue": "Explain robust estimation, tail risk, and assumption boundaries",
      "snapshotTools": "EDA workflow",
      "snapshotToolsValue": "Check fields, missingness, duplicates, and definitions before interpreting charts",
      "snapshotFocus": "Reviewable output",
      "snapshotFocusValue": "Connect code, tables, charts, and conclusions in one analysis trail",
      "workEyebrow": "Public writing",
      "workTitle": "Selected Essays",
      "workSubtitle": "The homepage focuses on reviewed essays and analysis notes.",
      "hrProjectKicker": "Public writing",
      "hrProjectTitle": "Data Analysis Articles",
      "hrProjectSummary": "Reviewed technical notes that show data audit, modeling assumptions, visualization interpretation, and explainable conclusions.",
      "hrFactModelLabel": "Model",
      "hrFactModelValue": "Unstructured recruiting information -> field extraction, weighted scoring, evidence gaps, and explainable decisions",
      "hrFactStackLabel": "Stack",
      "hrFactStackValue": "Python, pandas, visualization, mathematical notation, technical writing",
      "hrFactStatusLabel": "Status",
      "hrFactStatusValue": "Published articles only; private drafts and local materials stay offline",
      "hrWorkflowLink": "View workflow",
      "implementationKicker": "Writing process",
      "implementationTitle": "From raw observation to reviewable explanation",
      "implementationSubtitle": "Public notes show the analysis path, assumptions, and interpretation boundaries.",
      "implementationFlowBrowser": "Observe",
      "implementationFlowApi": "Audit",
      "implementationFlowStore": "Structure",
      "implementationFlowScore": "Interpret",
      "implementationFlowReview": "Explain",
      "implementationCaptureTitle": "Observation",
      "implementationCaptureText": "Start from raw variables, definitions, missingness, abnormal values, and uncertainty before making claims.",
      "implementationBackendTitle": "Data audit",
      "implementationBackendText": "Check structure, duplicates, missing cells, field roles, and data quality caveats before visualization.",
      "implementationDecisionTitle": "Interpretation",
      "implementationDecisionText": "Separate descriptive patterns from causal claims and keep assumptions visible.",
      "implementationWorkspaceTitle": "Output",
      "implementationWorkspaceText": "Turn analysis into readable notes, tables, figures, and concise explanations.",
      "writingEyebrow": "Published writing",
      "writingTitle": "Data Analysis and Statistics Essays",
      "writingSubtitle": "Two essays: one explains robust estimation, the other shows an HR Analytics EDA workflow.",
      "aboutEyebrow": "About",
      "aboutTitle": "Internship Direction and Core Strength",
      "footerLabel": "Personal technical blog"
    }
  }
};
