// Public homepage content edited by the local editor.
// This file is safe to publish: do not put private material or personal raw notes here.

window.siteContent = {
  "zh": {
    "profile": {
      "name": "Dale Anfer",
      "initials": "D",
      "title": "个人技术博客名片",
      "availability": "统计学习 / 数据分析 / 技术写作",
      "tagline": "这里记录我如何把不确定的数据问题拆成变量、假设、图表和可解释结论；文章尽量保留从直觉到验证的完整分析过程。",
      "bio": "这个博客用来沉淀我的统计学习、数据分析和建模笔记。相比展示结论，我更在意问题如何被定义、数据如何被审计、假设如何影响解释。",
      "email": "",
      "github": "https://github.com/sudoun"
    },
    "ui": {
      "brand": "blog",
      "titleSuffix": "个人技术博客名片",
      "navWork": "项目",
      "navImplementation": "实现",
      "navWriting": "写作",
      "navAbout": "关于",
      "primaryWork": "阅读文章",
      "primaryProjects": "GitHub 主页",
      "fitPanelKicker": "写作索引",
      "fitPanelTitle": "数学、数据与可解释分析笔记",
      "fitTargetLabel": "主题",
      "fitTargetValue": "稳健估计、EDA、数据口径、建模假设",
      "fitEvidenceLabel": "方法",
      "fitEvidenceValue": "从例子、代码、表格和图表中解释判断过程",
      "fitGithubLabel": "GITHUB",
      "fitGithubValue": "github.com/sudoun",
      "snapshotRole": "稳健估计",
      "snapshotRoleValue": "用异常值、尾部风险和假设边界理解估计器",
      "snapshotTools": "EDA 笔记",
      "snapshotToolsValue": "先检查字段、缺失、重复和口径，再解释分布",
      "snapshotFocus": "可复现解释",
      "snapshotFocusValue": "把代码、表格、图表和结论放在同一条分析链路里",
      "workEyebrow": "公开写作",
      "workTitle": "精选文章",
      "workSubtitle": "主页聚焦已经审核的公开文章和数据分析笔记。",
      "hrProjectKicker": "公开写作",
      "hrProjectTitle": "数据分析文章",
      "hrProjectSummary": "用公开技术文章展示数据审计、建模假设、图表解释和可复核结论。",
      "hrFactModelLabel": "模型",
      "hrFactModelValue": "非结构化招聘信息 → 字段抽取、权重评分、证据缺口、可解释决策",
      "hrFactStackLabel": "技术",
      "hrFactStackValue": "Python、pandas、可视化、数学符号、技术写作",
      "hrFactStatusLabel": "状态",
      "hrFactStatusValue": "只发布已审核文章，私人草稿和本地材料不公开",
      "hrWorkflowLink": "查看工作流",
      "implementationKicker": "写作过程",
      "implementationTitle": "从原始观察到可复核解释",
      "implementationSubtitle": "公开文章展示分析路径、假设边界和解释过程。",
      "implementationFlowBrowser": "观察",
      "implementationFlowApi": "审计",
      "implementationFlowStore": "结构化",
      "implementationFlowScore": "解释",
      "implementationFlowReview": "表达",
      "implementationCaptureTitle": "观察",
      "implementationCaptureText": "先看变量、定义、缺失、异常值和不确定性，再进入解释。",
      "implementationBackendTitle": "数据审计",
      "implementationBackendText": "在可视化前检查结构、重复、缺失、字段角色和数据质量限制。",
      "implementationDecisionTitle": "解释",
      "implementationDecisionText": "区分描述性模式和因果判断，并把假设写清楚。",
      "implementationWorkspaceTitle": "输出",
      "implementationWorkspaceText": "把分析整理成可读的笔记、表格、图表和简洁说明。",
      "writingEyebrow": "公开写作",
      "writingTitle": "数据分析与统计文章",
      "writingSubtitle": "两篇公开文章分别展示统计估计直觉和标准 EDA 流程：从异常值、缺失和重复项，到图表解释与建模边界。",
      "flowKicker": "写作方法",
      "flowTitle": "从观察到解释",
      "flowInputTitle": "观察",
      "flowInputText": "先看字段定义、样本量、缺失、异常值和不确定性。",
      "flowProcessTitle": "结构化",
      "flowProcessText": "把松散信息变成变量、类别、假设和可比较记录。",
      "flowAnalysisTitle": "解释",
      "flowAnalysisText": "用数学直觉判断关系、取舍、隐含信号和结果合理性。",
      "flowOutputTitle": "表达",
      "flowOutputText": "产出别人能复核的笔记、表格、排序和解释。",
      "proofKicker": "写作关注",
      "proofTitle": "这些文章关心什么",
      "proofSubtitle": "我希望每篇文章都能留下清楚的推理路径：概念从哪里来，数据有什么限制，结论依赖哪些假设。",
      "proofCleanTitle": "概念直觉",
      "proofCleanText": "从一个小例子进入主题，再把直觉翻译成公式、实验或图表。",
      "proofAnalysisTitle": "数据口径",
      "proofAnalysisText": "先说明字段、样本、缺失、异常值和预处理选择，再进入解释。",
      "proofDecisionTitle": "解释边界",
      "proofDecisionText": "区分描述、估计和判断，把结论成立所需要的条件写清楚。",
      "aboutEyebrow": "关于",
      "aboutTitle": "数学直觉、数据理解、可解释输出",
      "footerLabel": "个人技术博客名片",
    }
  },
  "en": {
    "profile": {
      "name": "Dale Anfer",
      "initials": "D",
      "title": "Personal Technical Blog and Portfolio",
      "availability": "Statistics / Data Analysis / Technical Writing",
      "tagline": "This site collects how I turn uncertain data questions into variables, assumptions, charts, and explainable conclusions. The essays keep the reasoning process visible.",
      "bio": "This blog is a place for my statistics, data analysis, and modeling notes. I care less about polished claims than about how a problem is defined, audited, tested, and interpreted.",
      "email": "",
      "github": "https://github.com/sudoun"
    },
    "ui": {
      "brand": "Technical Blog Card",
      "titleSuffix": "Personal Technical Blog",
      "navWork": "Work",
      "navImplementation": "Implementation",
      "navWriting": "Writing",
      "navAbout": "About",
      "primaryWork": "Read Essays",
      "primaryProjects": "GitHub Profile",
      "fitPanelKicker": "Writing index",
      "fitPanelTitle": "Notes on math, data, and explainable analysis",
      "fitTargetLabel": "Topics",
      "fitTargetValue": "Robust estimation, EDA, data definitions, modeling assumptions",
      "fitEvidenceLabel": "Method",
      "fitEvidenceValue": "Explain reasoning through examples, code, tables, and charts",
      "fitGithubLabel": "GitHub",
      "fitGithubValue": "github.com/sudoun",
      "snapshotRole": "Statistical sense",
      "snapshotRoleValue": "Explain robust estimation, tail risk, and assumption boundaries",
      "snapshotTools": "EDA workflow",
      "snapshotToolsValue": "Check fields, missingness, duplicates, and definitions before interpreting charts",
      "snapshotFocus": "Reviewable output",
      "snapshotFocusValue": "Connect code, tables, charts, and conclusions in one analysis trail",
      "workEyebrow": "Public writing",
      "workTitle": "Selected Essays",
      "workSubtitle": "The homepage focuses on reviewed essays and analysis notes.",
      "hrProjectKicker": "Public writing",
      "hrProjectTitle": "Data Analysis Articles",
      "hrProjectSummary": "Reviewed technical notes that show data audit, modeling assumptions, visualization interpretation, and explainable conclusions.",
      "hrFactModelLabel": "Model",
      "hrFactModelValue": "Unstructured recruiting information -> field extraction, weighted scoring, evidence gaps, and explainable decisions",
      "hrFactStackLabel": "Stack",
      "hrFactStackValue": "Python, pandas, visualization, mathematical notation, technical writing",
      "hrFactStatusLabel": "Status",
      "hrFactStatusValue": "Published articles only; private drafts and local materials stay offline",
      "hrWorkflowLink": "View workflow",
      "implementationKicker": "Writing process",
      "implementationTitle": "From raw observation to reviewable explanation",
      "implementationSubtitle": "Public notes show the analysis path, assumptions, and interpretation boundaries.",
      "implementationFlowBrowser": "Observe",
      "implementationFlowApi": "Audit",
      "implementationFlowStore": "Structure",
      "implementationFlowScore": "Interpret",
      "implementationFlowReview": "Explain",
      "implementationCaptureTitle": "Observation",
      "implementationCaptureText": "Start from raw variables, definitions, missingness, abnormal values, and uncertainty before making claims.",
      "implementationBackendTitle": "Data audit",
      "implementationBackendText": "Check structure, duplicates, missing cells, field roles, and data quality caveats before visualization.",
      "implementationDecisionTitle": "Interpretation",
      "implementationDecisionText": "Separate descriptive patterns from causal claims and keep assumptions visible.",
      "implementationWorkspaceTitle": "Output",
      "implementationWorkspaceText": "Turn analysis into readable notes, tables, figures, and concise explanations.",
      "writingEyebrow": "Published writing",
      "writingTitle": "Data Analysis and Statistics Essays",
      "writingSubtitle": "Two public essays show statistical estimation intuition and a standard EDA workflow: from outliers, missingness, and duplicates to chart interpretation and modeling boundaries.",
      "flowKicker": "Writing method",
      "flowTitle": "From Observation to Explanation",
      "flowInputTitle": "Observe",
      "flowInputText": "Inspect field definitions, sample size, missingness, abnormal values, and uncertainty.",
      "flowProcessTitle": "Structure",
      "flowProcessText": "Turn loose information into variables, categories, assumptions, and comparable records.",
      "flowAnalysisTitle": "Interpret",
      "flowAnalysisText": "Use mathematical intuition to judge relationships, tradeoffs, hidden signals, and result reasonableness.",
      "flowOutputTitle": "Explain",
      "flowOutputText": "Produce notes, tables, rankings, and explanations that can be reviewed by other people.",
      "proofKicker": "Writing focus",
      "proofTitle": "What These Essays Care About",
      "proofSubtitle": "Each essay tries to leave a clear reasoning trail: where the concept comes from, what the data can and cannot say, and which assumptions support the conclusion.",
      "proofCleanTitle": "Concept Intuition",
      "proofCleanText": "Start from a small example, then translate the intuition into formulas, experiments, or charts.",
      "proofAnalysisTitle": "Data Definition",
      "proofAnalysisText": "State fields, samples, missingness, outliers, and preprocessing choices before interpretation.",
      "proofDecisionTitle": "Interpretation Boundary",
      "proofDecisionText": "Separate description, estimation, and judgment, and make the required assumptions visible.",
      "aboutEyebrow": "About",
      "aboutTitle": "Math Intuition, Data Sense, Explainable Output",
      "footerLabel": "Personal technical blog card"
    }
  }
};
