// Public homepage content edited by the local editor.
// This file is safe to publish: do not put private material or personal raw notes here.

window.siteContent = {
  "zh": {
    "profile": {
      "name": "Dale Anfer",
      "initials": "D",
      "title": "个人技术博客名片",
      "availability": "HR / 数据分析 / 产品运营实习",
      "tagline": "我用数学建模和数据直觉，把复杂业务信息拆成变量、约束、假设和可解释结论；公开文章展示我的数据审计、统计理解和图表解释过程。",
      "bio": "我正在寻找 HR、数据分析和产品运营相关实习机会。我的核心优势是把信息整理成可复核的结构：先审计数据，再解释模型假设，最后输出清晰结论。",
      "email": "",
      "github": "https://github.com/sudoun"
    },
    "ui": {
      "brand": "blog",
      "titleSuffix": "个人技术博客名片",
      "navWork": "项目",
      "navImplementation": "实现",
      "navWriting": "写作",
      "navAbout": "关于",
      "primaryWork": "查看公开文章",
      "primaryProjects": "GitHub 主页",
      "fitPanelKicker": "给招聘方",
      "fitPanelTitle": "用公开文章证明分析过程的实习候选人",
      "fitTargetLabel": "目标方向",
      "fitTargetValue": "HR、数据分析、产品运营",
      "fitEvidenceLabel": "核心信号",
      "fitEvidenceValue": "统计直觉、数据审计、图表解释、可复核输出",
      "fitGithubLabel": "GITHUB",
      "fitGithubValue": "github.com/sudoun",
      "snapshotRole": "统计直觉",
      "snapshotRoleValue": "用稳健估计、尾部风险和假设边界解释数据现象",
      "snapshotTools": "EDA 流程",
      "snapshotToolsValue": "先检查字段、缺失、重复和口径，再解释图表",
      "snapshotFocus": "可复核输出",
      "snapshotFocusValue": "把代码、表格、图表和结论放在同一条分析链路里",
      "workEyebrow": "公开写作",
      "workTitle": "精选文章",
      "workSubtitle": "主页聚焦已经审核的公开文章和数据分析笔记。",
      "hrProjectKicker": "公开写作",
      "hrProjectTitle": "数据分析文章",
      "hrProjectSummary": "用公开技术文章展示数据审计、建模假设、图表解释和可复核结论。",
      "hrFactModelLabel": "模型",
      "hrFactModelValue": "非结构化招聘信息 → 字段抽取、权重评分、证据缺口、可解释决策",
      "hrFactStackLabel": "技术",
      "hrFactStackValue": "Python、pandas、可视化、数学符号、技术写作",
      "hrFactStatusLabel": "状态",
      "hrFactStatusValue": "只发布已审核文章，私人草稿和本地材料不公开",
      "hrWorkflowLink": "查看工作流",
      "implementationKicker": "写作过程",
      "implementationTitle": "从原始观察到可复核解释",
      "implementationSubtitle": "公开文章展示分析路径、假设边界和解释过程。",
      "implementationFlowBrowser": "观察",
      "implementationFlowApi": "审计",
      "implementationFlowStore": "结构化",
      "implementationFlowScore": "解释",
      "implementationFlowReview": "表达",
      "implementationCaptureTitle": "观察",
      "implementationCaptureText": "先看变量、定义、缺失、异常值和不确定性，再进入解释。",
      "implementationBackendTitle": "数据审计",
      "implementationBackendText": "在可视化前检查结构、重复、缺失、字段角色和数据质量限制。",
      "implementationDecisionTitle": "解释",
      "implementationDecisionText": "区分描述性模式和因果判断，并把假设写清楚。",
      "implementationWorkspaceTitle": "输出",
      "implementationWorkspaceText": "把分析整理成可读的笔记、表格、图表和简洁说明。",
      "writingEyebrow": "公开写作",
      "writingTitle": "数据分析与统计文章",
      "writingSubtitle": "两篇公开文章分别展示统计估计直觉和标准 EDA 流程：从异常值、缺失和重复项，到图表解释与建模边界。",
      "flowKicker": "工作流",
      "flowTitle": "我的分析方式",
      "flowInputTitle": "观察",
      "flowInputText": "先看字段定义、样本量、缺失、异常值和不确定性。",
      "flowProcessTitle": "结构化",
      "flowProcessText": "把松散信息变成变量、类别、假设和可比较记录。",
      "flowAnalysisTitle": "解释",
      "flowAnalysisText": "用数学直觉判断关系、取舍、隐含信号和结果合理性。",
      "flowOutputTitle": "表达",
      "flowOutputText": "产出别人能复核的笔记、表格、排序和解释。",
      "proofKicker": "能力信号",
      "proofTitle": "主页应该证明什么",
      "proofSubtitle": "我希望招聘方看到：我不只是操作工具，而是能理解模型、数据和输出背后的逻辑。",
      "proofCleanTitle": "数据直觉",
      "proofCleanText": "我关注数据暗示了什么：字段、分布、缺失、异常点，以及结论是否合理。",
      "proofAnalysisTitle": "建模假设",
      "proofAnalysisText": "我会先说明估计器、分类目标、缺失处理和图表结论依赖什么假设。",
      "proofDecisionTitle": "业务转译",
      "proofDecisionText": "我能把 HR、运营或业务问题转成字段、比较口径、风险提示和可执行结论。",
      "aboutEyebrow": "关于",
      "aboutTitle": "数学直觉、数据理解、可解释输出",
      "footerLabel": "个人技术博客名片",
    }
  },
  "en": {
    "profile": {
      "name": "Dale Anfer",
      "initials": "D",
      "title": "Personal Technical Blog and Portfolio",
      "availability": "HR / Data Analysis / Product Operations Internship",
      "tagline": "I use mathematical modeling and data intuition to turn messy business information into variables, assumptions, and explainable conclusions; the public essays show my data-audit and statistical reasoning process.",
      "bio": "I am looking for HR, data analysis, and product operations internships. My strongest signal is turning information into reviewable structure: audit the data, state the assumptions, and explain the output clearly.",
      "email": "",
      "github": "https://github.com/sudoun"
    },
    "ui": {
      "brand": "Technical Blog Card",
      "titleSuffix": "Personal Technical Blog",
      "navWork": "Work",
      "navImplementation": "Implementation",
      "navWriting": "Writing",
      "navAbout": "About",
      "primaryWork": "View Writing",
      "primaryProjects": "GitHub Profile",
      "fitPanelKicker": "For recruiters",
      "fitPanelTitle": "Intern candidate whose analysis process is visible in public writing",
      "fitTargetLabel": "Target roles",
      "fitTargetValue": "HR, data analysis, product operations",
      "fitEvidenceLabel": "Evidence",
      "fitEvidenceValue": "Statistical intuition, data audit, chart interpretation, reviewable output",
      "fitGithubLabel": "GitHub",
      "fitGithubValue": "github.com/sudoun",
      "snapshotRole": "Statistical sense",
      "snapshotRoleValue": "Explain robust estimation, tail risk, and assumption boundaries",
      "snapshotTools": "EDA workflow",
      "snapshotToolsValue": "Check fields, missingness, duplicates, and definitions before interpreting charts",
      "snapshotFocus": "Reviewable output",
      "snapshotFocusValue": "Connect code, tables, charts, and conclusions in one analysis trail",
      "workEyebrow": "Public writing",
      "workTitle": "Selected Essays",
      "workSubtitle": "The homepage focuses on reviewed essays and analysis notes.",
      "hrProjectKicker": "Public writing",
      "hrProjectTitle": "Data Analysis Articles",
      "hrProjectSummary": "Reviewed technical notes that show data audit, modeling assumptions, visualization interpretation, and explainable conclusions.",
      "hrFactModelLabel": "Model",
      "hrFactModelValue": "Unstructured recruiting information -> field extraction, weighted scoring, evidence gaps, and explainable decisions",
      "hrFactStackLabel": "Stack",
      "hrFactStackValue": "Python, pandas, visualization, mathematical notation, technical writing",
      "hrFactStatusLabel": "Status",
      "hrFactStatusValue": "Published articles only; private drafts and local materials stay offline",
      "hrWorkflowLink": "View workflow",
      "implementationKicker": "Writing process",
      "implementationTitle": "From raw observation to reviewable explanation",
      "implementationSubtitle": "Public notes show the analysis path, assumptions, and interpretation boundaries.",
      "implementationFlowBrowser": "Observe",
      "implementationFlowApi": "Audit",
      "implementationFlowStore": "Structure",
      "implementationFlowScore": "Interpret",
      "implementationFlowReview": "Explain",
      "implementationCaptureTitle": "Observation",
      "implementationCaptureText": "Start from raw variables, definitions, missingness, abnormal values, and uncertainty before making claims.",
      "implementationBackendTitle": "Data audit",
      "implementationBackendText": "Check structure, duplicates, missing cells, field roles, and data quality caveats before visualization.",
      "implementationDecisionTitle": "Interpretation",
      "implementationDecisionText": "Separate descriptive patterns from causal claims and keep assumptions visible.",
      "implementationWorkspaceTitle": "Output",
      "implementationWorkspaceText": "Turn analysis into readable notes, tables, figures, and concise explanations.",
      "writingEyebrow": "Published writing",
      "writingTitle": "Data Analysis and Statistics Essays",
      "writingSubtitle": "Two public essays show statistical estimation intuition and a standard EDA workflow: from outliers, missingness, and duplicates to chart interpretation and modeling boundaries.",
      "flowKicker": "Workflow",
      "flowTitle": "How I Analyze",
      "flowInputTitle": "Observe",
      "flowInputText": "Inspect field definitions, sample size, missingness, abnormal values, and uncertainty.",
      "flowProcessTitle": "Structure",
      "flowProcessText": "Turn loose information into variables, categories, assumptions, and comparable records.",
      "flowAnalysisTitle": "Interpret",
      "flowAnalysisText": "Use mathematical intuition to judge relationships, tradeoffs, hidden signals, and result reasonableness.",
      "flowOutputTitle": "Explain",
      "flowOutputText": "Produce notes, tables, rankings, and explanations that can be reviewed by other people.",
      "proofKicker": "Ability signal",
      "proofTitle": "What This Page Should Prove",
      "proofSubtitle": "I want recruiters to see a candidate who can understand models and data, not only operate tools.",
      "proofCleanTitle": "Data Intuition",
      "proofCleanText": "I care about what data implies: fields, distributions, missingness, abnormal points, and whether the conclusion is reasonable.",
      "proofAnalysisTitle": "Modeling Assumptions",
      "proofAnalysisText": "I state what each estimator, classification target, missing-value rule, and chart interpretation depends on.",
      "proofDecisionTitle": "Business Translation",
      "proofDecisionText": "I can turn HR, operations, or business questions into fields, comparison rules, risk notes, and actionable conclusions.",
      "aboutEyebrow": "About",
      "aboutTitle": "Math Intuition, Data Sense, Explainable Output",
      "footerLabel": "Personal technical blog card"
    }
  }
};
